'use client';

import { ThemeProvider } from "@/app/context/ThemeContext";

import Navigation from "@/components/app-nav/navigation";
import "./globals.css";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full h-lvh flex flex-col">
        {/* <div className="fixed z-50 bg-red-400 w-full h-0.5">

        </div> */}
        <ThemeProvider>
          <Navigation>
            {children}
          </Navigation>
        </ThemeProvider>

      </body>
    </html>
  );
}
